# Generated by Django 4.1.4 on 2022-12-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("product_price", models.IntegerField()),
                (
                    "product_img",
                    models.ImageField(default="test", upload_to="prod_img/"),
                ),
            ],
        ),
    ]
