# Generated by Django 4.1.4 on 2022-12-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0002_products"),
    ]

    operations = [
        migrations.CreateModel(
            name="latest_products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("la_prod_name", models.CharField(max_length=100)),
                ("la_prod_price", models.IntegerField()),
                (
                    "la_prod_image",
                    models.ImageField(default="test", upload_to="prod_img/"),
                ),
            ],
        ),
    ]
